# Toolset Definitions
# This file maps toolsets to their respective tool files.

TOOLSETS = {
    'archive_utilities': [
        'tools/archive/extract_archive.py',
    ],
    'data_utilities': [
        'tools/data/aggregate_stats.py',
        'tools/data/calculate_correlations.py',
        'tools/data/clean_dataset.py',
        'tools/data/clear_datasets.py',
        'tools/data/convert_format.py',
        'tools/data/encode_categorical.py',
        'tools/data/filter_dataset.py',
        'tools/data/impute_missing.py',
        'tools/data/merge_datasets.py',
        'tools/data/pivot_dataset.py',
        'tools/data/sample_dataset.py',
    ],
    'file_utilities': [
        'tools/file/create_directory.py',
        'tools/file/delete_file.py',
        'tools/file/file_size.py',
        'tools/file/list_files.py',
        'tools/file/move_file.py',
        'tools/file/read_file.py',
        'tools/file/search_text.py',
        'tools/file/write_to_file.py',
    ],
    'graphing_utilities': [
        'tools/graphing/clear_plots.py',
        'tools/graphing/draw_bar_plot.py',
        'tools/graphing/draw_boxplot.py',
        'tools/graphing/draw_comparison_plot.py',
        'tools/graphing/draw_heatmap.py',
        'tools/graphing/draw_histogram.py',
        'tools/graphing/draw_joint_plot.py',
        'tools/graphing/draw_kde_plot.py',
        'tools/graphing/draw_line_plot.py',
        'tools/graphing/draw_pair_plot.py',
        'tools/graphing/draw_reg_plot.py',
        'tools/graphing/draw_scatter_plot.py',
        'tools/graphing/draw_violin_plot.py',
        'tools/graphing/explore_dataset.py',
    ],
    'math_utilities': [
        'tools/math/absolute_value.py',
        'tools/math/add.py',
        'tools/math/ceiling.py',
        'tools/math/cos.py',
        'tools/math/divide.py',
        'tools/math/factorial.py',
        'tools/math/floor.py',
        'tools/math/gcd.py',
        'tools/math/log_base_10.py',
        'tools/math/mean.py',
        'tools/math/median.py',
        'tools/math/mode.py',
        'tools/math/multiply.py',
        'tools/math/natural_log.py',
        'tools/math/power.py',
        'tools/math/sin.py',
        'tools/math/square_root.py',
        'tools/math/standard_deviation.py',
        'tools/math/subtract.py',
        'tools/math/tan.py',
    ],
    'ml_utilities': [
        'tools/ml/train_linear_model.py',
    ],
    'network_utilities': [
        'tools/network/check_port.py',
        'tools/network/dns_lookup.py',
        'tools/network/download_file.py',
        'tools/network/fetch_url.py',
        'tools/network/get_ip_address.py',
        'tools/network/get_network_interfaces.py',
        'tools/network/ping_host.py',
    ],
    'reporting_utilities': [
        'tools/reporting/generate_pdf_report.py',
    ],
    'system_utilities': [
        'tools/system/get_cpu_usage.py',
        'tools/system/get_disk_space.py',
        'tools/system/get_env_variables.py',
        'tools/system/get_memory_usage.py',
        'tools/system/get_os_info.py',
        'tools/system/get_time.py',
        'tools/system/kill_process.py',
        'tools/system/list_processes.py',
        'tools/system/run_shell_command.py',
    ],
    'web_utilities': [
        'tools/web/scrape_html.py',
        'tools/web/search_web.py',
    ],
}
