# Toolset Definitions
# Maps toolset category names to lists of (path, description) tuples.
# Descriptions are used directly as the LLM tool description — be explicit
# about the EXACT args format so small models (qwen3:1.7b) call tools correctly.

TOOLSETS = {
    'archive_utilities': [
        ('tools/archive/extract_archive.py',
         'Extract a zip, tar, or gz archive. Args: path to the archive file. Example: "files/data.zip"'),
    ],
    'data_utilities': [
        ('tools/data/aggregate_stats.py',
         'Compute aggregate statistics (sum, mean, min, max, count) grouped by a column. Args: "<csv_path> <group_column> <value_column>". Example: "data/sales.csv region revenue"'),
        ('tools/data/calculate_correlations.py',
         'Calculate the Pearson correlation matrix for numeric columns in a CSV. Args: path to CSV file. Example: "data/scores.csv"'),
        ('tools/data/clean_dataset.py',
         'Remove duplicate rows and strip whitespace from string columns in a CSV. Args: "<input_csv> <output_csv>". Example: "data/raw.csv data/clean.csv"'),
        ('tools/data/clear_datasets.py',
         'Delete all CSV files in the data/ output directory to reset the workspace. Args: none.'),
        ('tools/data/convert_format.py',
         'Convert a data file between formats (csv, json, parquet). Args: "<input_file> <output_file>". Example: "data/input.csv data/output.json"'),
        ('tools/data/encode_categorical.py',
         'One-hot encode a categorical column in a CSV and save the result. Args: "<csv_path> <column_name> <output_csv>". Example: "data/survey.csv gender data/encoded.csv"'),
        ('tools/data/filter_dataset.py',
         'Filter rows in a CSV where a column matches a value. Args: "<csv_path> <column> <value> <output_csv>". Example: "data/sales.csv region North data/north_sales.csv"'),
        ('tools/data/impute_missing.py',
         'Fill missing values in a CSV column with the column mean. Args: "<csv_path> <column_name> <output_csv>". Example: "data/survey.csv age data/filled.csv"'),
        ('tools/data/merge_datasets.py',
         'Merge two CSV files on a shared key column. Args: "<csv1> <csv2> <key_column> <output_csv>". Example: "data/orders.csv data/customers.csv id data/merged.csv"'),
        ('tools/data/pivot_dataset.py',
         'Pivot a CSV: reshape rows into columns. Args: "<csv_path> <index_col> <columns_col> <values_col> <output_csv>". Example: "data/sales.csv date region revenue data/pivot.csv"'),
        ('tools/data/sample_dataset.py',
         'Randomly sample N rows from a CSV. Args: "<csv_path> <n_rows> <output_csv>". Example: "data/large.csv 100 data/sample.csv"'),
    ],
    'file_utilities': [
        ('tools/file/create_directory.py',
         'Create a new directory (and any missing parent directories). Args: path of directory to create. Example: "output/reports/2024"'),
        ('tools/file/create_file.py',
         'Create a new empty file at the given path. Args: file path to create. Example: "output/notes.txt"'),
        ('tools/file/delete_file.py',
         'Delete a file at the given path. Args: file path to delete. Example: "output/old_report.txt"'),
        ('tools/file/file_size.py',
         'Get the size of a file in bytes. Args: file path. Example: "data/dataset.csv"'),
        ('tools/file/list_files.py',
         'List all files in a directory. Args: directory path. Example: "output/" or "." for current directory.'),
        ('tools/file/move_file.py',
         'Move or rename a file. Args: "<source_path> <destination_path>". Example: "output/draft.txt output/final.txt"'),
        ('tools/file/read_file.py',
         'Read and return the full text contents of a file. Args: file path. Example: "output/report.txt"'),
        ('tools/file/search_text.py',
         'Search for a text string inside a file and return matching lines. Args: "<file_path> <search_term>". Example: "output/log.txt ERROR"'),
        ('tools/file/write_to_file.py',
         'Write (or append) text content to a file. Args: "<file_path> <text_content>". Example: "output/notes.txt \\"Hello world\\""'),
    ],
    'graphing_utilities': [
        ('tools/graphing/clear_plots.py',
         'Delete all saved plot image files from the output directory. Args: none.'),
        ('tools/graphing/draw_bar_plot.py',
         'Draw a bar chart from a CSV. Args: "<csv_path> <x_column> <y_column> <output_image>". Example: "data/sales.csv month revenue output/bar.png"'),
        ('tools/graphing/draw_boxplot.py',
         'Draw a box plot showing distribution of a numeric column, optionally grouped. Args: "<csv_path> <value_column> [group_column] <output_image>". Example: "data/scores.csv score group output/box.png"'),
        ('tools/graphing/draw_comparison_plot.py',
         'Draw a side-by-side bar chart comparing two numeric columns. Args: "<csv_path> <x_col> <y1_col> <y2_col> <output_image>". Example: "data/results.csv month actual predicted output/compare.png"'),
        ('tools/graphing/draw_heatmap.py',
         'Draw a heatmap of a numeric matrix or correlation table from a CSV. Args: "<csv_path> <output_image>". Example: "data/corr.csv output/heatmap.png"'),
        ('tools/graphing/draw_histogram.py',
         'Draw a histogram of a numeric column. Args: "<csv_path> <column_name> <output_image>". Example: "data/scores.csv score output/hist.png"'),
        ('tools/graphing/draw_joint_plot.py',
         'Draw a joint scatter + distribution plot for two numeric columns. Args: "<csv_path> <x_column> <y_column> <output_image>". Example: "data/stats.csv height weight output/joint.png"'),
        ('tools/graphing/draw_kde_plot.py',
         'Draw a KDE (kernel density estimate) smooth distribution curve for a numeric column. Args: "<csv_path> <column_name> <output_image>". Example: "data/ages.csv age output/kde.png"'),
        ('tools/graphing/draw_line_plot.py',
         'Draw a line chart from a CSV. Args: "<csv_path> <x_column> <y_column> <output_image>". Example: "data/timeseries.csv date value output/line.png"'),
        ('tools/graphing/draw_pair_plot.py',
         'Draw a pairplot matrix of all numeric column combinations. Args: "<csv_path> <output_image>". Example: "data/iris.csv output/pairs.png"'),
        ('tools/graphing/draw_reg_plot.py',
         'Draw a scatter plot with a linear regression line. Args: "<csv_path> <x_column> <y_column> <output_image>". Example: "data/housing.csv size price output/reg.png"'),
        ('tools/graphing/draw_scatter_plot.py',
         'Draw a scatter plot of two numeric columns. Args: "<csv_path> <x_column> <y_column> <output_image>". Example: "data/stats.csv height weight output/scatter.png"'),
        ('tools/graphing/draw_violin_plot.py',
         'Draw a violin plot showing distribution shape of a numeric column. Args: "<csv_path> <value_column> [group_column] <output_image>". Example: "data/scores.csv score group output/violin.png"'),
        ('tools/graphing/explore_dataset.py',
         'Generate a quick visual summary of a CSV dataset (histograms for each numeric column). Args: "<csv_path> <output_image>". Example: "data/dataset.csv output/explore.png"'),
    ],
    'math_utilities': [
        ('tools/math/absolute_value.py',
         'Return the absolute (non-negative) value of a number. Args: a single number. Example: "-7.5"'),
        ('tools/math/add.py',
         'Add two numbers together. Args: two space-separated numbers. Example: "12 8"'),
        ('tools/math/ceiling.py',
         'Round a number UP to the nearest integer. Args: a single decimal number. Example: "4.2"'),
        ('tools/math/cos.py',
         'Calculate the cosine of an angle in radians. Args: angle in radians as a number. Example: "1.5708"'),
        ('tools/math/divide.py',
         'Divide the first number by the second. Args: two space-separated numbers. Example: "100 4"'),
        ('tools/math/factorial.py',
         'Calculate the factorial of a non-negative integer (n!). Args: a single non-negative integer. Example: "5"'),
        ('tools/math/floor.py',
         'Round a number DOWN to the nearest integer. Args: a single decimal number. Example: "4.9"'),
        ('tools/math/gcd.py',
         'Find the greatest common divisor of two integers. Args: two space-separated integers. Example: "48 18"'),
        ('tools/math/log_base_10.py',
         'Calculate the base-10 logarithm of a number. Args: a single positive number. Example: "1000"'),
        ('tools/math/mean.py',
         'Calculate the arithmetic mean (average) of a list of numbers. Args: comma-separated numbers with NO spaces. Example: "10,20,30,40"'),
        ('tools/math/median.py',
         'Find the median (middle value) of a list of numbers. Args: comma-separated numbers with NO spaces. Example: "3,1,4,1,5,9"'),
        ('tools/math/mode.py',
         'Find the mode (most frequent value) of a list of numbers. Args: comma-separated numbers with NO spaces. Example: "1,2,2,3,3,3"'),
        ('tools/math/multiply.py',
         'Multiply two numbers together. Args: two space-separated numbers. Example: "7 6"'),
        ('tools/math/natural_log.py',
         'Calculate the natural logarithm (base e) of a number. Args: a single positive number. Example: "2.718"'),
        ('tools/math/power.py',
         'Raise a base number to an exponent (base^exp). Args: two space-separated numbers: base then exponent. Example: "2 10"'),
        ('tools/math/sin.py',
         'Calculate the sine of an angle in radians. Args: angle in radians as a number. Example: "3.1416"'),
        ('tools/math/square_root.py',
         'Calculate the square root of a non-negative number. Args: a single non-negative number. Example: "144"'),
        ('tools/math/standard_deviation.py',
         'Calculate the standard deviation of a list of numbers. Args: comma-separated numbers with NO spaces. Example: "2,4,4,4,5,5,7,9"'),
        ('tools/math/subtract.py',
         'Subtract the second number from the first. Args: two space-separated numbers. Example: "50 18"'),
        ('tools/math/tan.py',
         'Calculate the tangent of an angle in radians. Args: angle in radians as a number. Example: "0.7854"'),
    ],
    'ml_utilities': [
        ('tools/ml/train_linear_model.py',
         'Train a simple linear regression model on a CSV and report R² score and coefficients. Args: "<csv_path> <target_column>". Example: "data/housing.csv price"'),
    ],
    'network_utilities': [
        ('tools/network/check_port.py',
         'Check whether a TCP port is open on a host. Args: "<hostname> <port>". Example: "google.com 443"'),
        ('tools/network/dns_lookup.py',
         'Perform a DNS lookup and return IP addresses for a hostname. Args: hostname. Example: "github.com"'),
        ('tools/network/download_file.py',
         'Download a file from a URL and save it locally. Args: "<url> <output_path>". Example: "https://example.com/data.csv data/data.csv"'),
        ('tools/network/fetch_url.py',
         'Fetch the text content of a web page or API endpoint via HTTP GET. Args: URL. Example: "https://api.github.com"'),
        ('tools/network/get_ip_address.py',
         'Get the local machine\'s IP address. Args: none.'),
        ('tools/network/get_network_interfaces.py',
         'List all active network interfaces and their IP addresses. Args: none.'),
        ('tools/network/ping_host.py',
         'Ping a host to check if it is reachable on the network. Args: hostname or IP address. Example: "8.8.8.8"'),
    ],
    'reporting_utilities': [
        ('tools/reporting/generate_pdf_report.py',
         'Generate a PDF report from a text or markdown string. Args: "<output_pdf_path> <report_text>". Example: "output/report.pdf \\"Summary: all tests passed\\""'),
    ],
    'system_utilities': [
        ('tools/system/get_cpu_usage.py',
         'Get the current CPU usage percentage of the machine. Args: none.'),
        ('tools/system/get_disk_space.py',
         'Get available and total disk space for the current drive. Args: none.'),
        ('tools/system/get_env_variables.py',
         'List all environment variables currently set in the shell session. Args: none.'),
        ('tools/system/get_memory_usage.py',
         'Get the current RAM usage (used, available, total) in MB. Args: none.'),
        ('tools/system/get_os_info.py',
         'Get operating system information: OS name, version, and architecture. Args: none.'),
        ('tools/system/get_time.py',
         'Get the current date and time. Args: none.'),
        ('tools/system/kill_process.py',
         'Kill a running process by its PID. Args: process ID (integer). Example: "1234"'),
        ('tools/system/list_processes.py',
         'List all currently running processes with their PID and name. Args: none.'),
        ('tools/system/run_shell_command.py',
         'Run an arbitrary shell command and return its output. Args: the command string. Example: "echo hello world"'),
    ],
    'web_utilities': [
        ('tools/web/scrape_html.py',
         'Scrape and return the visible text content from a web page URL. Args: URL. Example: "https://en.wikipedia.org/wiki/Python_(programming_language)"'),
        ('tools/web/search_web.py',
         'Search the web using DuckDuckGo and return the top result titles and URLs. Args: search query string. Example: "latest Python release"'),
    ],
}
