import os
import glob

def tool(func):
    """Decorator to mark a function as a tool."""
    func._is_tool = True
    return func

@tool
def clear_plots():
    """
    Removes all PNG plot files generated by the graphing tools in the current directory.
    """
    try:
        # Find all .png files in the current working directory
        plots = glob.glob("*.png")
        if not plots:
            return "No plot files found to remove."
        
        for plot in plots:
            os.remove(plot)
            
        return f"Successfully removed {len(plots)} plot files."
    except Exception as e:
        return f"Error clearing plots: {str(e)}"

if __name__ == "__main__":
    print(clear_plots())
